## Multi Layer Perceptron ( MLP )  __________________________________

Importar as bibliotecas

In [3]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import normalize 
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
import tensorflow as tf
from keras.utils import np_utils

### Carregar Base de Dados

In [4]:
data=pd.read_csv("data/folhas.csv")
data.sample(10)

SepalLength  SepalWidth  PetalLength  PetalWidth          Species
41           4.5         2.3          1.3         0.3      Iris-setosa
147          6.5         3.0          5.2         2.0   Iris-virginica
12           4.8         3.0          1.4         0.1      Iris-setosa
104          6.5         3.0          5.8         2.2   Iris-virginica
116          6.5         3.0          5.5         1.8   Iris-virginica
32           5.2         4.1          1.5         0.1      Iris-setosa
37           4.9         3.1          1.5         0.1      Iris-setosa
55           5.7         2.8          4.5         1.3  Iris-versicolor
69           5.6         2.5          3.9         1.1  Iris-versicolor
31           5.4         3.4          1.5         0.4      Iris-setosa

###  Codificar as categorias

In [5]:
##### SE OS TIPOS DE FOLHAS JÁ VIEREM CLASSIFICADOS POR ÍNDICES, ISSO NÃO É NECESSÁRIO ###
# data.loc[data["Species"]=="Iris-setosa","Species"]=0
# data.loc[data["Species"]=="Iris-versicolor","Species"]=1
# data.loc[data["Species"]=="Iris-virginica","Species"]=2



     SepalLength  SepalWidth  PetalLength  PetalWidth Species
108          6.7         2.5          5.8         1.8       2
119          6.0         2.2          5.0         1.5       2
136          6.3         3.4          5.6         2.4       2
77           6.7         3.0          5.0         1.7       1
85           6.0         3.4          4.5         1.6       1
97           6.2         2.9          4.3         1.3       1
131          7.9         3.8          6.4         2.0       2
78           6.0         2.9          4.5         1.5       1
138          6.0         3.0          4.8         1.8       2
101          5.8         2.7          5.1         1.9       2


### Separar dados descritivos das classes

In [6]:
# Shuffle
data=data.iloc[np.random.permutation(len(data))]
print(data.sample(10))

X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

print("Shape of X",X.shape)
print("Shape of y",y.shape)

### Dividir dados para treinamento, validação e teste

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
import numpy as np

# Normalizar os dados
X_normalized = normalize(X, axis=0)

'''
O ORIGINAL SEPARAVA ASSIM, O ADAIR DISSE PRA USAR 8 IMAGENS PROS TESTES NÉ? QUANTAS FOLHAS TEM EM CADA IMAGEM E QUANTAS TEM NO TOTAL?
70% - conjunto de treinamento
20% - conjunto de validação
10% - conjunto de teste
'''
X_train_val, X_test, y_train_val, y_test = train_test_split(X_normalized, y, test_size=0.1, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.22, random_state=42)

# Transformar os rótulos em categorias ### 6 CLASSES = [Folhado, Araçá, Quaresmeira, Pessegueiro, Coleus, Uva do mato]
num_classes = 6
y_train = np_utils.to_categorical(y_train, num_classes)
y_val = np_utils.to_categorical(y_val, num_classes)
y_test = np_utils.to_categorical(y_test, num_classes)

## Arquitetura do MLP

In [21]:
model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(16,input_dim=4,activation='relu'))
model.add(tf.keras.layers.Dense(64,activation='relu'))
model.add(tf.keras.layers.Dense(64,activation='relu'))

#model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 16)                80        
                                                                 
 dense_13 (Dense)            (None, 64)                1088      
                                                                 
 dense_14 (Dense)            (None, 64)                4160      
                                                                 
 dense_15 (Dense)            (None, 3)                 195       
                                                                 
Total params: 5,523
Trainable params: 5,523
Non-trainable params: 0
_________________________________________________________________


### Treinar a rede

In [24]:
# class_weights = {
#     0: 1.0,  # peso da classe 0
#     1: 1.0,  # peso da classe 1
#     2: 1.0,  # peso da classe 2
# }

model.fit(X_train,
          y_train,
          validation_split=0.2,
          batch_size=16,
          epochs=50,
          verbose=1,
        #   class_weight=class_weights
          )

Epoch 1/75
6/6 [==============================] - 0s 81ms/step - loss: 1.0777 - accuracy: 0.4048 - val_loss: 1.0763 - val_accuracy: 0.3333
Epoch 2/75
6/6 [==============================] - 0s 11ms/step - loss: 1.0689 - accuracy: 0.4048 - val_loss: 1.0687 - val_accuracy: 0.3333
Epoch 3/75
6/6 [==============================] - 0s 9ms/step - loss: 1.0591 - accuracy: 0.3690 - val_loss: 1.0594 - val_accuracy: 0.3333
Epoch 4/75
6/6 [==============================] - 0s 8ms/step - loss: 1.0465 - accuracy: 0.3810 - val_loss: 1.0452 - val_accuracy: 0.3333
Epoch 5/75
6/6 [==============================] - 0s 9ms/step - loss: 1.0309 - accuracy: 0.4762 - val_loss: 1.0278 - val_accuracy: 0.6190
Epoch 6/75
6/6 [==============================] - 0s 9ms/step - loss: 1.0128 - accuracy: 0.6071 - val_loss: 1.0054 - val_accuracy: 0.7143
Epoch 7/75
6/6 [==============================] - 0s 9ms/step - loss: 0.9923 - accuracy: 0.6667 - val_loss: 0.9777 - val_accuracy: 0.8095
Epoch 8/75
6/6 [================

Epoch 60/75
6/6 [==============================] - 0s 9ms/step - loss: 0.1097 - accuracy: 0.9762 - val_loss: 0.0714 - val_accuracy: 1.0000
Epoch 61/75
6/6 [==============================] - 0s 9ms/step - loss: 0.1076 - accuracy: 0.9524 - val_loss: 0.0735 - val_accuracy: 1.0000
Epoch 62/75
6/6 [==============================] - 0s 18ms/step - loss: 0.1042 - accuracy: 0.9643 - val_loss: 0.0672 - val_accuracy: 1.0000
Epoch 63/75
6/6 [==============================] - 0s 11ms/step - loss: 0.1026 - accuracy: 0.9524 - val_loss: 0.0664 - val_accuracy: 1.0000
Epoch 64/75
6/6 [==============================] - 0s 9ms/step - loss: 0.0984 - accuracy: 0.9643 - val_loss: 0.0706 - val_accuracy: 1.0000
Epoch 65/75
6/6 [==============================] - 0s 11ms/step - loss: 0.1051 - accuracy: 0.9524 - val_loss: 0.0630 - val_accuracy: 1.0000
Epoch 66/75
6/6 [==============================] - 0s 9ms/step - loss: 0.1014 - accuracy: 0.9524 - val_loss: 0.0621 - val_accuracy: 1.0000
Epoch 67/75
6/6 [=======

### Testar

In [26]:
# Fazer previsões nos dados de teste
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# Calcular a matriz de confusão
matriz_confusao = confusion_matrix(np.argmax(y_test, axis=1), y_pred_classes)

# Calcular a acurácia
acuracia = accuracy_score(np.argmax(y_test, axis=1), y_pred_classes)

# Calcular a pontuação F1
f1 = f1_score(np.argmax(y_test, axis=1), y_pred_classes, average='macro')

print("Matriz de Confusão:")
print(matriz_confusao)
print("Acurácia:", acuracia)
print("Pontuação F1:", f1)


1/1 [==============================] - 0s 82ms/step
Matriz de Confusão:
[[6 0 0]
 [0 5 0]
 [0 0 4]]
Acurácia: 1.0
Pontuação F1: 1.0
